# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# fnm
FNM_PATH="~/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

CARGO_ENV="~/.cargo/env"
[ -f $CARGO_ENV ] && source $CARGO_ENV

# tell fzf to not map these command I'm using gf and gd in cmd mode
FZF_CTRL_T_COMMAND=
# FZF_ALT_C_COMMAND=
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
bind -m vi-command -x '"gf": "fzf-file-widget"'
bind -m vi-command '"gd": "\C-z\ec\C-z"'
# Open in tmux popup if on tmux, otherwise use --height mode
FZF_DEFAULT_OPTS='--tmux center'

# toggle between block <-> line cursor in cmd or insertion mode
bind "set show-mode-in-prompt on"
bind 'set vi-cmd-mode-string "\1\e[2 q\2"'
bind 'set vi-ins-mode-string "\1\e[6 q\2"'

# add my local bin directory
export PATH=~/bin:~/.local/bin:/usr/local/bin:$PATH
# vim mode
set -o vi

