import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
# family = "HackNerdFont"
# family = "JetBrainsMonoNerdFont"
# family = "GoMonoNerdFontMono"
family = "FiraCodeNerdFont"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Control"

[scrolling]
history = 10000

[shell]
args = ["new", "-As", "Theo"]
program = "tmux"

[window]
decorations = "None"
startup_mode = "Maximized"
 opacity = 0.98
